// Trading mode selection
export const FINANCE_NOTIFICATION_MODE = {
  BUY: 'Buy',
  SELL: 'Sell',
} as const;

export type FinanceNotificationModeType = typeof FINANCE_NOTIFICATION_MODE[keyof typeof FINANCE_NOTIFICATION_MODE];

// Individual condition types
export const FINANCE_NOTIFICATION_CONDITION_TYPE = {
  GREATER_THAN: 'GreaterThan',
  LESS_THAN: 'LessThan',
  THREE_RED_SOLDIERS: 'ThreeRedSoldiers',
  THREE_RIVER_EVENING_STAR: 'ThreeRiverEveningStar',
  TWO_TAKURI_LINES: 'TwoTakuriLines',
  SWALLOW_RETURN: 'SwallowReturn',
  FIREWORKS: 'Fireworks',
  OKAJI_THREE_CROWS: 'OkajiThreeCrows',
  FALLING_STONES: 'FallingStones',
  BULLISH_HARAMI_CROSS: 'BullishHaramiCross',
  BEARISH_HARAMI_CROSS: 'BearishHaramiCross',
  HAWK_REVERSAL: 'HawkReversal',
  THREE_DARK_STARS: 'ThreeDarkStars',
  SHOOTING_STAR: 'ShootingStar',
} as const;

export type FinanceNotificationConditionType = typeof FINANCE_NOTIFICATION_CONDITION_TYPE[keyof typeof FINANCE_NOTIFICATION_CONDITION_TYPE];

// Condition groups by mode
export const BUY_CONDITIONS = [
  FINANCE_NOTIFICATION_CONDITION_TYPE.GREATER_THAN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.LESS_THAN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_RED_SOLDIERS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_RIVER_EVENING_STAR,
  FINANCE_NOTIFICATION_CONDITION_TYPE.TWO_TAKURI_LINES,
  FINANCE_NOTIFICATION_CONDITION_TYPE.SWALLOW_RETURN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.BULLISH_HARAMI_CROSS,
] as const;

export const SELL_CONDITIONS = [
  FINANCE_NOTIFICATION_CONDITION_TYPE.GREATER_THAN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.LESS_THAN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.FIREWORKS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.OKAJI_THREE_CROWS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.FALLING_STONES,
  FINANCE_NOTIFICATION_CONDITION_TYPE.BEARISH_HARAMI_CROSS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.HAWK_REVERSAL,
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_DARK_STARS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.SHOOTING_STAR,
] as const;

export const FINANCE_NOTIFICATION_TIME_FRAME = {
  ONE_MINUTE: '1',
} as const;

export type FinanceNotificationTimeFrameType = typeof FINANCE_NOTIFICATION_TIME_FRAME[keyof typeof FINANCE_NOTIFICATION_TIME_FRAME];

// Notification frequency control
export const FINANCE_NOTIFICATION_FREQUENCY = {
  EXCHANGE_START_ONLY: 'ExchangeStartOnly',
  MINUTE_LEVEL: 'MinuteLevel',
  TEN_MINUTE_LEVEL: 'TenMinuteLevel',
  HOURLY_LEVEL: 'HourlyLevel',
} as const;

export type FinanceNotificationFrequencyType = typeof FINANCE_NOTIFICATION_FREQUENCY[keyof typeof FINANCE_NOTIFICATION_FREQUENCY];

// Condition type categories for timing
export const DAILY_CONDITION_TYPES = [
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_RED_SOLDIERS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_RIVER_EVENING_STAR,
  FINANCE_NOTIFICATION_CONDITION_TYPE.TWO_TAKURI_LINES,
  FINANCE_NOTIFICATION_CONDITION_TYPE.SWALLOW_RETURN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.FIREWORKS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.OKAJI_THREE_CROWS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.FALLING_STONES,
  FINANCE_NOTIFICATION_CONDITION_TYPE.BULLISH_HARAMI_CROSS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.BEARISH_HARAMI_CROSS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.HAWK_REVERSAL,
  FINANCE_NOTIFICATION_CONDITION_TYPE.THREE_DARK_STARS,
  FINANCE_NOTIFICATION_CONDITION_TYPE.SHOOTING_STAR,
] as const;

export const MINUTE_LEVEL_CONDITION_TYPES = [
  FINANCE_NOTIFICATION_CONDITION_TYPE.GREATER_THAN,
  FINANCE_NOTIFICATION_CONDITION_TYPE.LESS_THAN,
] as const;

// New type for condition with frequency configuration
export interface FinanceNotificationConditionWithFrequency {
  type: FinanceNotificationConditionType;
  frequency: FinanceNotificationFrequencyType;
}
