import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import BasicAppBar from '@client-common/components/surfaces/AppBars/BasicAppBar';
import LinkMenu from '@client-common/components/navigations/Menus/LinkMenu';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const menuItems = [
  { title: 'Home', url: '/' }
];

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <head>
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BasicAppBar
          center={
            <div>Next.js Sample</div>
          }
          right={
            <LinkMenu menuItems={menuItems} />
          }
        />
        {children}
      </body>
    </html>
  );
}
