import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import AuthUtil from '@client-common/auth/AuthUtil';
import SignInButton from '@client-common/components/inputs/Buttons/SignInButton';
import SignoutButton from '@client-common/components/inputs/Buttons/SignOutButton';
import BasicAppBar from '@client-common/components/surfaces/AppBars/BasicAppBar';
import LinkMenu, { MenuItemData } from '@client-common/components/navigations/Menus/LinkMenu';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

async function getMenuItems(): Promise<MenuItemData[]> {
  const session = await AuthUtil.getServerSession();

  const menuItems = [
    { title: 'Home', url: '/' },
    { title: 'Sample Button', url: '/sample-button' },
    { title: 'Sample Date Picker', url: '/sample-date-picker' },
    { title: 'Sample Stacks', url: '/sample-stacks' },
    { title: 'Sample Select', url: '/sample-select' },
    { title: 'Sample Tab', url: '/sample-tab' },
    { title: 'Sample Text Field', url: '/sample-text-field' },
    { title: 'Sample Radio Group', url: '/sample-radio-group' }
  ];

  if (session) {
    menuItems.push({ title: 'User Data', url: '/user-data' });
  }

  return menuItems;
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await AuthUtil.getServerSession();

  return (
    <html lang="ja">
      <head>
        <link rel="manifest" href="/manifest.webmanifest" />
      </head>
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <BasicAppBar
          center={
            <div>Next.js Sample</div>
          }
          right={
            <>
              {session ? (
                <SignoutButton />
              ) : (
                <SignInButton />
              )}
              <LinkMenu menuItems={await getMenuItems()} />
            </>
          }
        />
        {children}
      </body>
    </html>
  );
}
